### ISSUE TITLE
DNSSec

### ISSUE THREAD

**Issue by flanfly** [das-labor/server#10]
Der dnssec signer läuft auf casino. "Nur" die dane / tlsa Einträge welche durch letsencrypt häufiger aktualisiert werden sind problematisch.

**Comment by TheRadialActive** [comment]
Sollte hinten angestellt werden oder sogar komplett gestrichen werden, da der wirkliche Nutzen an Sicherheit nicht klar ist und wir zumindest die Möglichkeit haben, DNSSec nachträglich einzupflegen.

**Comment by lambdafu** [comment]
Wird wohl einfach weiterlaufen können: Der bind ist migriert und der Rest der Infrastruktur ist auf casino im Labor.
Update: Ok, hab erst später gesehen, dass die DANE/TLSA-Einträge durch letsencrypt beeinflusst werden.  Muss untersucht werden.

**Comment by TheRadialActive** [comment]
Haben wir nicht mehr und ist deswegen überflüssig.
