### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by flanfly** [das-labor/server#11]

**Comment by lambdafu** [comment]
Potentially blocks some other services (or at least makes them more attractive), such as mumble.

**Comment by flanfly** [comment]
Do we have/want a mumble. I'm sure there are alternatives that work with LDAP.

**Comment by lambdafu** [comment]
Maybe jitsi is enough, then mumble is not needed.  With blocking I meant the other way round: It's easier to configure mumble (or similar) once LDAP is ready, so LDAP should come early.  I didn't mean to say that introducing LDAP prevents mumble or anything like that!

**Comment by flanfly** [comment]
Works with wiki and blog. Closing.
