### ISSUE TITLE
MediaGoblin

### ISSUE THREAD

**Issue by flanfly** [das-labor/server#20]
Do we still want one?

**Comment by TheRadialActive** [comment]
Problem: Es scheint nur auf PostgreSQL zu laufen, was die Idee "alles auf mysql" laufen zu lassen brechen würde. Es wird derzeit von @runealbut Dockerimages ausprobiert.

**Comment by TheRadialActive** [comment]
Zudem besteht die Idee Videos auf media.ccc.de zu hosten, aber für Bilder und Co MediaGoblin zu verwenden.

**Comment by TheRadialActive** [comment]
Wir benötigen Mediagoblin nun nicht mehr, weil das meiste über das SemanticMediaWiki umgesetzt werden kann. Gerade weil wir jetzt den Blog ins Wiki übertragen haben.
