### ISSUE TITLE
Add wp-cli to blog container.

### ISSUE THREAD

**Issue by lambdafu** [das-labor/server#36]
It's useful for quick admin tasks like resetting passwords.  Installation works, but --allow-root should be the default.  http://wp-cli.org/

**Comment by lambdafu** [comment]
Current workaround:

```
/var/www/html# php wp-cli.phar --allow-root user list
```

**Comment by TheRadialActive** [comment]
The blog isn't available anymore. All blog posts are now in SemanticMediaWiki.
