### ISSUE TITLE
TLS not working

### ISSUE THREAD

**Issue by flanfly** [das-labor/server#7]
The LFE does not handle TLS.

**Comment by flanfly** [comment]
Reenable FORCE_SSL_ADMIN in wp-config.php after this issue has been resolved.

**Comment by zaolin** [comment]
Let's encrypt is now activated and usable!

**Comment by zaolin** [comment]
Let's encrypt is now activated and usable!

**Comment by flanfly** [comment]
TLS is working with an self-signed cert for now. See #35 and #38.
